# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.version={{ .Version }}"

universal_binaries:
  - replace: false

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

changelog:
  disable: true
